general {
    # Никакой блокировки перед сном
    # После пробуждения включить мониторы обратно
    after_sleep_cmd = hyprctl dispatch dpms on

    # Не ждать lock screen перед sleep
    inhibit_sleep = 1
}

# 10 минут бездействия — выключить мониторы
# listener {
#     timeout = 600
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on
# }

# 30 минут бездействия — спящий режим
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
